### ISSUE TITLE
Necessário função que retorne um vetor com a letras que o jogador acertou

### ISSUE THREAD

**Issue by kauanpolydoro** [kauanpolydoro/git-trabalho-final-utfpr#3]
A função deve retornar um vetor para que o CSS seja aplicado corretamente na linha do GRID onde o usuário indicou uma palavra para adivinhação.

- [x] Deve retornar 0 caso a letra não exista na palavra
- [x] Deve retornar 1 caso a letra exista na palavra. porém o usuário indicou a posição incorreta
- [x] Deve retornar 2 caso a letra exista na palavra e o usuário indicou a posição correta

Exemplo:

Palavra do jogo: **CARRO**
Palavara digitada: **CARTA**

Retorno da função:

`[ 2 , 2 , 2 , 0 , 1 ]`

**Comment by misaelbraga** [comment]
Issue fechada na PR #8
